### ISSUE TITLE
Asset Transactions do not include all burn actions

### ISSUE THREAD

**Issue by theeldermillenial** [blockfrost/blockfrost-backend-ryo#101]
I think this is an API issue.

What I want to do is get the time of each burn and mint for an asset. The asset history gives you a `tx_hash` and an `action` that provides this information, but no date.

The asset transactions endpoint gives you a `block_time` and `tx_hash`, but no `action`.

I pulled in all values from the asset transactions endpoint and all transactions from the asset history endpoint. When I try to match each `tx_hash` in the asset history to the asset transactions, I find that all `mint` actions are in the transaction history, but only about 10% of the `burn` actions are the in the transaction history.

I am doing this in Python. I can provide a short script that can show what I am saying. I can also provide some reference assets and how many mismatched transactions there are.

**Comment by sorki** [comment]
Hi,

the script and example assets would be helpful so we can investigate further.

**Comment by mmahut** [comment]
@theeldermillenial do you have more information about this issue please?

**Comment by vladimirvolek** [comment]
Please reopen if you are still experiencing problems.

**Comment by theeldermillenial** [comment]
@vladimirvolek Sorry for the delay. I will provide additional info in the next week. However, I do not have the ability to reopen. Should I just ping you?

**Comment by mmahut** [comment]
> @vladimirvolek Sorry for the delay. I will provide additional info in the next week. However, I do not have the ability to reopen. Should I just ping you?

Ping.
