### ISSUE TITLE
How can we verify the signed Transaction?

### ISSUE THREAD

**Issue by golddydev** [blockfrost/blockfrost-backend-ryo#126]
I am now facing an issue.
I was trying to verify the signed transaction and its signer.
I signed the transaction using signTx() (CIP-30)

Can anyone help me?

Thank you.

**Comment by slowbackspace** [comment]
Hi @eageringdev, could you further explain what is the issue you are facing?

**Comment by golddydev** [comment]
Hi, So what I am going to do is to verify the signed Transaction and its signer.

So on the frontend, user will sign the transaction and on the backend, I'd like to verify that whether he really is the signer of this transaction.

**Comment by golddydev** [comment]
Actually, I found this answer.
I extract the public Key from signature and requried signer from transaction body.
And verify the transaction.

https://github.com/Emurgo/cardano-serialization-lib/issues/640#issuecomment-1712841213

This is my solution.
What do you think?

**Comment by slowbackspace** [comment]
That's great you were able to figure it out! It seems that your issue is not really related to Blockfrost backend so I'm closing this.

**Comment by golddydev** [comment]
Yes, that is right.
In the first place, I have a thought maybe I could this this using blockfrost backend.
Haha
