### ISSUE TITLE
Missing Docker entrypoint

### ISSUE THREAD

**Issue by Zaczero** [blockfrost/blockfrost-backend-ryo#22]
The https://github.com/blockfrost/blockfrost-backend-ryo/blob/master/Dockerfile is missing the `ENTRYPOINT` directive _(which I assume should point to `["/app/blockfrost-backend"]`)_ causing the image to exit immediately after run.

**Comment by sorki** [comment]
It indeed does, I've opened #23 to add it. Thank you!
