### ISSUE TITLE
incorrect results `/governance/dreps/{dRepId}`

### ISSUE THREAD

**Issue by jinglescode** [blockfrost/blockfrost-backend-ryo#227]
Endpoint (mainnet):
`/governance/dreps/drep_script190xv8v32n43luhu9ag05s5mvcs6079lg4zghzyg3j9vlgle68y3`

response:
```
{
  active: false,
  active_epoch: null,
  amount: "0",
  drep_id: "drep190xv8v32n43luhu9ag05s5mvcs6079lg4zghzyg3j9vlgsm80cs",
  has_script: false,
  hex: "2bccc3b22a9d63fe5f85ea1f48536cc434ff17e8a8917111119159f4",
}
```

Expected results:
- this drep ID should be active, see [adastat](https://adastat.net/dreps/drep1yv4uesaj92wk8ljlsh4p7jzndnzrflchaz5fzug3zxg4naqkpeas3), [cardanoscan](https://cardanoscan.io/drep/drep1yv4uesaj92wk8ljlsh4p7jzndnzrflchaz5fzug3zxg4naqkpeas3)
- has_script should be `true`
- `/governance/dreps/drep_script190xv8v32n43luhu9ag05s5mvcs6079lg4zghzyg3j9vlgle68y3/metadata` (mainnet) expect metadata data (not 404)

**Comment by slowbackspace** [comment]
Hi @jinglescode, the data for the drep are ineed incorrect (they are for keyHash variant which is also registered). We'll deploy fix for this issue shortly.

However it looks like the metadata will remain unavailable. Adastat provides a hint why this happen
> Hash mismatch when fetching metadata from https://2pzt5hfjckkkpzfl.public.blob.vercel-storage.com/drep/Mesh-yHdyc5bngMgjYtQ4xWULpTvIxpf3RN.jsonld. Expected "5174bef3136dde95498a42c9d5bda16dc79bb09e3fbbc8cc4f92ece5a393498c" but got "25764e675edde5e1de56ba014ce659bada2728019d3d2df3d6f6e0fdcdb399fa".
