### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by Wbsba** [blockfrost/blockfrost-backend-ryo#26]
can request /genesis 
but request other  error 
{
    "status_code": 500,
    "error": "Internal Server Error",
    "message": "An unexpected response was received from the backend."
}

**Comment by slowbackspace** [comment]
Hi @Wbsba! 
What is the `network` value inside your config file? 
Could you please paste logs from the backend itself? It should contain the reason behind the error.

**Comment by Wbsba** [comment]
I think my configuration is wrong ,tnx
