### ISSUE TITLE
CORS not set on 429 rate limit responses.

### ISSUE THREAD

**Issue by samuelWilliams99** [blockfrost/blockfrost-backend-ryo#30]
I'm unable to handle a rate limit response in the browser without CORS, as the browser omits it.
I also cannot use `no-cors`, as these requests require non-simple headers (specifically `projectId`).

How to recreate:
- Send many requests (more than 10 per second) in the frontend, via JS, attempt to catch rate limiting errors

Expected behaviour:
- Get back a message with a status of 429, handle it normally

Actual behaviour:
- CORS error in console quoting the 429 return code, uncatchable by browser design.

Suggested fix:
- Add `access-control-allow-origin: *` to 429 errors

**Comment by mmahut** [comment]
Closing as this issue is not related to `blockfrost-backend-ryo` but rather to the hosted blockfrost.io.

We are going to add CORS headers to 429 shorty on hosted.
