### ISSUE TITLE
/utils/txs/evaluate MediaType issue

### ISSUE THREAD

**Issue by martap79** [blockfrost/blockfrost-backend-ryo#32]
consuming /utils/txs/evaluate spits out below error. Same action (same data) works perfectly fine using the public endpoints.
running the latest docker image (0cc7767f979bdc03df48ee45e884e01f98a2c81290aa2706d2aa445c4ea8a7e7).

```
raise ApiError(request_response)
blockfrost.utils.ApiError: {'error': 'Unsupported Media Type', 'message': 'Unsupported Media Type: application/cbor', 'status_code': 415}
```

Any idea what could be the issue here? Other endpoints work perfectly fine.

**Comment by martap79** [comment]
support confirmed this endpoint is not supported in RYO as it depends on ogmios.

**Comment by vladimirvolek** [comment]
I fixed the error message in https://github.com/blockfrost/blockfrost-backend-ryo/pull/33.
