### ISSUE TITLE
EvaluateTx endpoint

### ISSUE THREAD

**Issue by martap79** [blockfrost/blockfrost-backend-ryo#38]
Endpoint /utils/txs/evaluate is non functional in RYO as it depends on ogmios. Would be great to build in support for it, and have it point to a locally running ogmios instance if available.

**Comment by mmahut** [comment]
The hosted `/utils/tx/evaluate` endpoint is just a simple proxy to Ogmios. If you are already running Ogmios, just proxy that endpoint to it. We might add this endpoint in the future once we will able to create with Lucid or other library without the need for a live cardano-node instance, but for now, we decided it is not worth adding it to RYO directly.
