### ISSUE TITLE
Ignore pagination when needed

### ISSUE THREAD

**Issue by mmahut** [blockfrost/blockfrost-backend-ryo#41]
Some customers running _ryo_ internally would like to have a special use case where they want to receive an entire, paginated response from the backend.

Let's introduce a new header `unpaginated` that when set, the ryo will provide an entire blob response without pagination.

**Comment by 1000101** [comment]
> Some customers running _ryo_ internally would like to have a special use case where they want to receive an entire, paginated response from the backend.

unpaginated, right?

> Let's introduce a new header unpaginated that when set, the ryo will provide an entire blob response without pagination.

Would you mind calling it `unpaged` instead of `unpaginated`? It feels kind of cumbersome.
