### ISSUE TITLE
custom indices

### ISSUE THREAD

**Issue by martap79** [blockfrost/blockfrost-backend-ryo#42]
Noticed the custom indices which made a HUGE difference for me on some of the endpoints, thanks for that!, but unfortunately not on all. Some endpoints are still a factor 20(??!) slower then the public endpoints. just 2 examples that are really slow are _/addresses/{address}/utxos/{asset}_ and _/txs/{hash}/utxos_. unfortunately I'm not a DBA and can't troubleshoot this, but I do see quite a few seq table scans for these queries which leads me to believe there are more custom indices needed?

I can provide the query analysis if that's helpful.

**Comment by 1000101** [comment]
Hi, I believe the list of indices is complete. Any other improvements are taking place on the infrastructure side.

However, if you could share more details, ideally `EXPLAIN ANALYZE` and list of indices (`\d+ table_name` on which seq lookup instead of idx scan is performed), that would be great to see what's really going on.

**Comment by martap79** [comment]
hope this is what u were asking for... not too familiar with the db side of things... :)
Tx!

[q1.txt](https://github.com/blockfrost/blockfrost-backend-ryo/files/10310759/q1.txt)
[q2.txt](https://github.com/blockfrost/blockfrost-backend-ryo/files/10310760/q2.txt)

**Comment by 1000101** [comment]
Which version of db sync are you using? Can you please paste the output of `\d+ script` as well? Thanks!

**Comment by martap79** [comment]
using version 13.0.5

[d_script.txt](https://github.com/blockfrost/blockfrost-backend-ryo/files/10315405/d_script.txt)

**Comment by sorki** [comment]
Thanks for looking into this! I've created a [PR for cardano-db-sync](https://github.com/input-output-hk/cardano-db-sync/pull/1329) with two missing indexes we've identified based on the files you provided.

We can't reproduce the sequential scan on scripts table (although it doesn't have significant performance impact), query planner for us (using PostgreSQL 14) does index scan. What PostgreSQL version are you running?

**Comment by martap79** [comment]
hi sorki, tx for that. I am using 14 as well.
I added the 2 proposed indices in your PR but only seeing a slight improvement in q2, and no improvement in q1. I added an updated explain analyze in case needed.

[q1_nr2.txt](https://github.com/blockfrost/blockfrost-backend-ryo/files/10320247/q1_nr2.txt)
[q2_nr2.txt](https://github.com/blockfrost/blockfrost-backend-ryo/files/10320248/q2_nr2.txt)

**Comment by 1000101** [comment]
Hey @martap79! 
q1 - I believe there's no further improvement possible (index-wise)
q2 - If you added new indices, you might need to update the planner/statistics to pick them up

**Comment by 1000101** [comment]
Hey @martap79!
q1 - I believe there's no further improvement possible (index-wise)
q2 - If you added new indices, you might need to update the planner statistics to pick them up

i.e. in both cases, run `ANALYZE`
