### ISSUE TITLE
Order doesn't sort results in "Address UTXOs of a given asset" endpoint

### ISSUE THREAD

**Issue by fabioDMFerreira** [blockfrost/blockfrost-backend-ryo#45]
I realized that the order parameter is handled here.
https://github.com/blockfrost/blockfrost-backend-ryo/blob/master/src/routes/addresses/index.ts#L528

I don't know if blockfrost servers are not updated with the last version or whether there is a bug in the SQL query.

**Comment by 1000101** [comment]
Hi @fabioDMFerreira, thanks for the report! Would you mind sharing an example / call where this happens? Thanks!

**Comment by fabioDMFerreira** [comment]
I realized there are no issues. It was a problem on my end. Thank you
