### ISSUE TITLE
Unable to pull docker image

### ISSUE THREAD

**Issue by SamDelaney** [blockfrost/blockfrost-backend-ryo#5]
I'm getting `manifest unknown` when I try to pull the docker image. 

<img width="673" alt="image" src="https://user-images.githubusercontent.com/20246757/195197706-426a5d96-3585-4a3b-ac4f-8b2b5d7cae7b.png">

When I look at the Dockerhub page (https://hub.docker.com/r/blockfrost/backend-ryo) I see no tags listed. I believe publishing tags will fix the issue, but I'm not super familiar with Docker so take my advice with a grain of salt.

<img width="986" alt="image" src="https://user-images.githubusercontent.com/20246757/195198212-7def4a1c-6158-46ae-8a5c-f9a2441a3ec4.png">

My team is working with Kubernetes so it would be awesome to have the convenience of the Docker image. Thanks in advance!

**Comment by mmahut** [comment]
Thank you for reporting this issue, I'm looking at why it is not listed publically.
