### ISSUE TITLE
Nix flake and NixOS module

### ISSUE THREAD

**Issue by aciceri** [blockfrost/blockfrost-backend-ryo#50]
Hey, if I opened a PR making this repo a flake, would you accept it?
I would also write a NixOS module to run Blockfrost.

Actually this is something that I'll do next days anyway, but obviously I would prefer keeping it upstream.
Just tell me if you want me to open a PR.

**Comment by mmahut** [comment]
@aciceri yes, please! :)

**Comment by aciceri** [comment]
I'll update the fork next days, keep an eye on it and tell me if you like how I'm doing it, please.
