### ISSUE TITLE
System start endpoint may not be returning the correct value

### ISSUE THREAD

**Issue by klntsky** [blockfrost/blockfrost-backend-ryo#52]
Could you please take a look at this?

There's a difference between Ogmios response and Blockfrost:

https://github.com/Plutonomicon/cardano-transaction-lib/pull/1377#issue-1517559580

**Comment by sorki** [comment]
Hi, thanks! 

I've linked a PR fixing `system_start` value and the difference between `/network/eras` end values for last entry is already fixed (and deployed on preview) in https://github.com/blockfrost/blockfrost-backend-ryo/pull/48

Will close when both fixes are in place.

**Comment by klntsky** [comment]
Thanks!

**Comment by mmahut** [comment]
This has been released.
