### ISSUE TITLE
Cardano node IPC socket instead of HTTP

### ISSUE THREAD

**Issue by aciceri** [blockfrost/blockfrost-backend-ryo#56]
Is it possible? How?

**Comment by mmahut** [comment]
It would be probably, but definitely outside of scope of blockfrost backend at this moment, as the node iteself provides access only to the current state snapshot and no historical data.

**Comment by aciceri** [comment]
Definitely makes sense, I've opened this issue before finding out that blockfrost uses `cardano-db-sync` and I forgot to close it, my fault.
