### ISSUE TITLE
Custom Cardano network

### ISSUE THREAD

**Issue by aciceri** [blockfrost/blockfrost-backend-ryo#75]
Let's suppose that I'm running a private network and a `cardano-db-sync` instance, would it be possible to use blockfrost? What should I pass as `network` in the configuration file? Is it used only to correctly query the tokens registry? In this case I guess I could simply pass `mainnet` and never call an API that queries itself the token registry (or re-implement a dummy token registry API).

**Comment by vladimirvolek** [comment]
Please check this https://github.com/blockfrost/blockfrost-backend-ryo/issues/72

**Comment by aciceri** [comment]
Ooops, I missed that issue. In my case it wouldn't be a testnet but I guess there is no difference.
I'm closing this, thanks.
