### ISSUE TITLE
Getting pool registration parameters

### ISSUE THREAD

**Issue by klntsky** [blockfrost/blockfrost-backend-ryo#82]
It looks like it is impossible to get pool registration parameters as they were provided during registration, in particular, pool metadata hash and URL are missing.

Ogmios [provides](https://github.com/CardanoSolutions/ogmios/blob/be859d6cc4adae512da31358e4870098ff741e83/docs/static/ogmios.wsp.json#L3382) them via `poolParameters` query endpoint, so having this feature would be highly appreaciated by us ([CTL](https://github.com/Plutonomicon/cardano-transaction-lib/)), because we want to be able to claim feature parity between Blockfrost and Ogmios as query layer backends.

Would it be possible to add this info to the responses?

Example pool with non-empty URL on preview network: `pool1leml52hm4fcp3hhe4zye08qz27llhj7d339p3gs0tl85cstx59q`.

**Comment by mmahut** [comment]
I think this information is provided within the registration transaction:

```
$ curl https://cardano-preview.blockfrost.io/api/v0/pools/pool1leml52hm4fcp3hhe4zye08qz27llhj7d339p3gs0tl85cstx59q/updates
[
  {
    "tx_hash": "4575bdf477454868d142327ae859d0440c5b2ada02a0d82de6927000a9b7d64d",
    "cert_index": 0,
    "action": "registered"
  }
]
```

```
$ curl https://cardano-preview.blockfrost.io/api/v0/txs/4575bdf477454868d142327ae859d0440c5b2ada02a0d82de6927000a9b7d64d/pool_updates jq '.[].metadata | .url,.hash'
"https://tinyurl.com/intrtpreview"
"b9e21ae6844cd61c812c3d5aec7dbe6f8099962fe1e952d51f297258ba89879f"
```

Is this what you are looking for?

**Comment by mmahut** [comment]
@klntsky please, feel free to re-open this issue if this is not this case.
