### ISSUE TITLE
`/utils/txs/evaluate` does not support additonal UTxOs

### ISSUE THREAD

**Issue by klntsky** [blockfrost/blockfrost-backend-ryo#85]
Ability to provide additional UTxOs at the stage of ExUnits evaluation is essential when implementing transaction chaining, because the query layer does not know (yet) about newly created UTxOs.

Ogmios [does support this](https://ogmios.dev/mini-protocols/local-tx-submission/#additional-utxo-set), but it looks like in Blockfrost this parameter is not passed properly.

**Comment by vladimirvolek** [comment]
We are working on this.

**Comment by vladimirvolek** [comment]
https://docs.blockfrost.io/#tag/Cardano-Utilities/paths/~1utils~1txs~1evaluate~1utxos/post
